language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t mattclaflin/docker-react -f Dockerfile.dev .

script:
  - docker run mattclaflin/docker-react npm run test -- --coverage